[package]
name = "gateway-testkit"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
axum.workspace = true
bytes.workspace = true
gateway-domain = { path = "../gateway-domain" }
http.workspace = true
serde.workspace = true
tokio.workspace = true
uuid.workspace = true

[dev-dependencies]
http-body-util.workspace = true

[lints]
workspace = true
